### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by ehiggs** [v0y4g3r/prom-write-request-bench#3]
These are really nice benchmarks and could benefit the prost project. Could you add a LICENSE file, so it's explicit whether this work can be used in the prost project?

If that sounds like a good idea to you then prost has Apache v2 license.

**Comment by v0y4g3r** [comment]
> These are really nice benchmarks and could benefit the prost project. Could you add a LICENSE file, so it's explicit whether this work can be used in the prost project?
> 
> If that sounds like a good idea to you then prost has Apache v2 license.

Thanks, you remind me that there's some code from rust-protobuf and I should add their license on top of these files.
